---
commitizen:
  name: cz_conventional_commits
  tag_format: 0.1.0
  update_changelog_on_bump: true
  version_provider: pep621
  version_scheme: pep440
  ----
  feat(user_data): добавление функции сохранения данных о пользователе

  Добавлена функция `save_user_data`, которая сохраняет данные о пользователе в JSON-файл.

  Также обновлены обработчики команд `/start`, `/help` и текстовых сообщений, чтобы использовать новую функцию `save_user_data`.



  fix(echo): исправление ошибки с отображением текста

  Была исправлена ошибка, при которой бот неправильно отображал текстовые сообщения пользователей в функции `echo`.

  Теперь бот корректно отображает текст в ответ на текстовые сообщения пользователей.



  docs: обновление комментариев и документации

  Обновлены комментарии к функциям `start`, `help`, `echo` и `save_user_data`, чтобы они были в стиле docstring.

  Также добавлено описание структуры Conventional Commits и типы коммитов в файле.

  Плюс небольшие исправления опечаток и улучшения формулировок в других частях кода.


